### ISSUE TITLE
On turn-on error shown

### ISSUE THREAD

**Issue by shelldandy** [Benjamin-Dobell/nvidia-update#23] opened 2018-05-03 13:57 UTC
This doesn't really affect me, more of a doubt if this is normal to happen. I get this screen 100% when turning my customac on:

<img width="812" alt="lwscreenshot 2018-05-03 at 8 47 41 am" src="https://user-images.githubusercontent.com/7088511/39580848-bc5707ac-4eaf-11e8-9adb-dafbaf76715c.png">

Pastebin:
https://pastebin.com/0jtUHJgm

Skimming it seems related to nvidia kexts that's why I'm asking if its related to here or if I need to tweak my config file or something.

Cheers!

**Comment by Benjamin-Dobell** [comment] 2018-05-03 14:03
Given the crash is within nVidia's drivers at runtime I doubt the issue is related to this project - as we just install the drivers. You could perhaps report this to nVidia, although it may be related to other nVidia-related kexts you have installed on your system.

Based on the information at hand, I can't see being something we can reasonably resolve as something as this project, so I'm going to close this issue for now.

However, you're welcome to update this issue with any additional information you come across, and if there's evidence nvidia-update plays a role then I'll be happy to reopen the issue.

**Closed by Benjamin-Dobell** 2018-05-03 14:03 UTC
